site_name: Instituto Águas Primordiais
site_url: https://andredor19.github.io/Kabbalah-das-Aguas-Primordiais/
use_directory_urls: true
theme:
  name: material
  language: pt
  logo: images/logo.svg
  favicon: images/favicon.svg
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo noturno
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.share
extra_css:
  - styles/mystical.css
  - styles/hero.css
nav:
  - Início: index.md
  - Interface Universal: interface_universal.html
  - Guia de Debug WS: debug_websocket.md
  - Protocolo Vivaldi:
    - Visão Geral: PR_FIX_PROTOCOLO_VIVALDI.md
    - Vortex Player: vivaldi/vortex_player.html
  - Sobre: sobre.md
  - Aulas:
    - "Introdução": "aulas/01-introducao.md"
    - "Letras Hebraicas": "aulas/02-letras-hebraicas.md"
    - "Tarô Cabalístico": "aulas/03-taro-cabalistico.md"
    - "Comando Consciente": "aulas/16-comando-consciente-da-realidade.md"
  - Oráculo-Mestre: oraculo.html