name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jinja2
      - name: Renderizar exemplo
        run: |
          python scripts/render.py schema/exemplo_dados.yaml build/exemplo.md
      - name: Publicar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: mapas-renderizados
          path: build/