# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main", "principal"]
  pull_request:
    branches: ["main", "principal"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Verificação se existem arquivos .ts para teste
      - name: Check for TypeScript files
        id: check-ts
        run: |
          TS_FILES=$(find . -name "*.ts" -not -path "./node_modules/*" | wc -l)
          echo "ts_files_count=$TS_FILES" >> $GITHUB_OUTPUT

      - name: Run linter
        if: steps.check-ts.outputs.ts_files_count != '0'
        run: deno lint || true

      - name: Run tests
        if: steps.check-ts.outputs.ts_files_count != '0'
        run: deno test -A || true
