name: Gerar e Publicar Relatório PSICO Semanal

on:
  schedule:
    - cron: '0 3 * * 0'  # Domingo às 03:00 UTC
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch main
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas jinja2 weasyprint

    - name: Rodar script de relatório
      run: |
        python scripts/psico_report.py

    - name: Configurar git para gh-pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Clonar branch gh-pages
      run: |
        git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || git checkout --orphan gh-pages
        rm -rf gh-pages/*
        cp -r reports/* gh-pages/
        cd gh-pages
        git add .
        git commit -m "Atualizar relatório semanal PSICO - $(date +%Y-%m-%d)"
        git push origin gh-pages
