name: Validar Markdown e Links

on:
  push:
    branches: [ "main", "principal" ]
  pull_request:
    branches: [ "main", "principal" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci

    - name: Validate Markdown
      run: |
        npx markdownlint '**/*.md' || true

    - name: Validate Links
      run: |
        # Pular validação de links por enquanto, pode ser adicionada posteriormente
        echo "Link validation skipped"
